# Adapted from https://github.com/zizmorcore/zizmor/blob/9796151bc1ce936b14982d2b53b882fa9d4279a7/docs/integrations.md?plain=1#L15-L42
name: GitHub Actions security analysis with zizmor (reusable workflow)

on:
  workflow_call:

permissions: {}

jobs:
  zizmor:
    name: Run zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required for upload-sarif (used by zizmor-action) to upload SARIF files.
      contents: read # Only needed for private repos. Needed to clone the repo.
      actions: read # Only needed for private repos. Needed for upload-sarif to read workflow run info.
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@71321a20a9ded102f6e9ce5718a2fcec2c4f70d8 # v0.5.2
